language: elixir
elixir:
  - 1.4.1
otp_release:
  - 19.0
sudo: false
addons:
  postgresql: '9.4'
env:
  - MIX_ENV=test
before_install:
  - mix local.rebar --force
  - mix local.hex --force
  - nvm install 7.7.2
install:
  - mix deps.get
  - npm install
before_script:
  - mix do ecto.create, ecto.migrate
script:
  - mix test
  - npm test
