language: elixir
elixir:
  - 1.4.1
otp_release:
  - 19.0
sudo: false
addons:
  postgresql: '9.4'
env:
  - MIX_ENV=test
  - NODE_VERSION="7.7.2"
before_install:
  - mix local.rebar --force
  - mix local.hex --force
  - nvm install $NODE_VERSION
install:
  - mix deps.get
  - npm install
before_script:
  - mix do ecto.create, ecto.migrate
script:
  - mix test
  - npm test
